### ISSUE TITLE
profitCheckProgramTs fix

### ISSUE THREAD

**Issue by adharna** [AlexRubik/rude-bot-solana#3]
When you will fix [profitCheckProgramTs](https://github.com/AlexRubik/rude-bot-solana/tree/main/profitCheckProgramTs) ?

**Comment by AlexRubik** [comment]
> When you will fix [profitCheckProgramTs](https://github.com/AlexRubik/rude-bot-solana/tree/main/profitCheckProgramTs) ?

@adharna Please describe exactly what you have tried and what problems you are running into. Give me context and the steps to reproduce your issue, thanks!

**Comment by AlexRubik** [comment]
@adharna This file you are referring to is an example file that you would add (or use as a reference) to your node app written in typescript. If you want to add this to your node app then you can refer to the imports at the top of the file and add them to your existing package.json. If you are creating a solana transaction in your app, you can use this code to guarantee a specified token's balance will not decrease if the transaction is confirmed. If the transaction will cause a decrease in the specified token's balance then the transaction is designed to fail.

https://rude-bot-org.gitbook.io/
